### ISSUE TITLE
Update stylesheet after adding new blocks/elements

### ISSUE THREAD

**Issue by ErlanBazarov** [Box-Of-Hats/Bem-VSCode-Extension#41] opened 2021-07-27 10:59 UTC
It will be great if the stylesheet would update with new blocks/elements when you add them to HTML

**Comment by Box-Of-Hats** [comment] 2021-07-27 13:02
Thanks for the suggestion. I agree that it would be a great feature to have :) 

This is a duplicate of #23 so I'll close this issue

**Closed** 2021-07-27 13:03 UTC
